### ISSUE TITLE
A question for channel pruning on  mobilenet

### ISSUE THREAD

**Issue by WashingtonTsai** [jack-willturner/DeepCompression-PyTorch#3]
Thank you,your code enlightens me.I have trained mobilenet on CIFAR10,and then I got 87% acurracy rate.Then I use deep_compress function,after i use sparsify function,I have found the weights of kernel in some layer  are all zero,it means when I use channel prue,I will loss all the following layer? Have i done something wrong?Thank you for your time!

**Comment by jack-willturner** [comment]
Sorry for the slow reply. 

This code is quite out of date because of updates to PyTorch. I'll take a look at this in the coming week - though the repo might need some overhauling.

**Comment by jack-willturner** [comment]
I've overhauled the repository now and done some testing - I don't believe this issue occurs any more.

However, I have only included code for ResNet-based architectures. I will extend this to MobileNetv2 and beyond in the coming months.
